-- AgriDrone Guardian — Migration 0002: Crop Reports
-- ---------------------------------------------------------------------------
-- Non-destructive and idempotent. Safe to run more than once.
-- Run in: Supabase Dashboard → SQL Editor → New query → paste → Run.
-- Requires migration 0001 (campaigns) to have been applied first.
--
-- Stores real crop reports generated by the AI Advisor from real diagnoses.
-- Reference column types match the existing tables:
--   fields.id          -> text
--   campaigns.id       -> uuid
--   flight_captures.id -> bigint
--   flights.flight_id  -> text  (soft reference, no hard FK)
-- ---------------------------------------------------------------------------

create extension if not exists "pgcrypto";

create table if not exists public.reports (
  id              uuid primary key default gen_random_uuid(),
  report_type     text not null default 'image'
                  check (report_type in ('image','flight','campaign','field')),
  title           text not null,
  field_id        text references public.fields(id) on delete set null,
  campaign_id     uuid references public.campaigns(id) on delete set null,
  flight_id       text,
  capture_id      bigint references public.flight_captures(id) on delete set null,
  report_markdown text,
  report_json     jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now()
);

create index if not exists reports_created_at_idx on public.reports(created_at desc);
create index if not exists reports_campaign_idx   on public.reports(campaign_id);
create index if not exists reports_flight_idx     on public.reports(flight_id);
create index if not exists reports_type_idx       on public.reports(report_type);

-- ── Row Level Security ──────────────────────────────────────────────────────
-- PROTOTYPE-GRADE anon read/write (matches the rest of the app). Tighten to
-- auth.uid() before production.
alter table public.reports enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'reports'
      and policyname = 'reports_anon_all'
  ) then
    create policy reports_anon_all on public.reports
      for all to anon, authenticated using (true) with check (true);
  end if;
end $$;

-- Verify with:  select id, report_type, title, created_at from public.reports;
