/// A real crop report stored in the `reports` table, generated by the AI
/// Advisor from real diagnosis/campaign/flight data.
class CropReport {
  final String id;
  final String reportType; // image | flight | campaign | field
  final String title;
  final String? reportMarkdown;
  final Map<String, dynamic> reportJson;
  final String? campaignId;
  final String? flightId;
  final int? captureId;
  final String? fieldId;
  final DateTime? createdAt;

  const CropReport({
    required this.id,
    required this.reportType,
    required this.title,
    this.reportMarkdown,
    this.reportJson = const {},
    this.campaignId,
    this.flightId,
    this.captureId,
    this.fieldId,
    this.createdAt,
  });

  factory CropReport.fromRow(Map<String, dynamic> row) {
    return CropReport(
      id: row['id'] as String,
      reportType: (row['report_type'] as String?) ?? 'image',
      title: (row['title'] as String?)?.trim().isNotEmpty == true
          ? row['title'] as String
          : 'Crop Report',
      reportMarkdown: row['report_markdown'] as String?,
      reportJson: row['report_json'] is Map
          ? Map<String, dynamic>.from(row['report_json'] as Map)
          : const {},
      campaignId: row['campaign_id'] as String?,
      flightId: row['flight_id'] as String?,
      captureId: (row['capture_id'] as num?)?.toInt(),
      fieldId: row['field_id'] as String?,
      createdAt: row['created_at'] != null
          ? DateTime.tryParse(row['created_at'] as String)
          : null,
    );
  }

  String get typeLabel {
    switch (reportType) {
      case 'flight':
        return 'Flight Report';
      case 'campaign':
        return 'Campaign Report';
      case 'field':
        return 'Field Report';
      default:
        return 'Image Report';
    }
  }
}
